### ISSUE TITLE
shows message for Visual Voicemail

### ISSUE THREAD

**Issue by GoogleCodeExporter** [everythingandroid/android-smspopup#104]
```
What steps will reproduce the problem?
1.if you have/are using visual voicemail...call yourself
2.leave voicemail
3.wait for popup from sender 901-6

What is the expected output? What do you see instead?
expected output is nothing. instead i see a popup when I get a voicemail 
indicating that I should call a 408 number as I was left a message by 
Sprint voice or something like that.  Although over half the time instead 
of the number to call, it gave the variable string instead as if it wasn't 
able to correctly parse a value.


What version of the product are you using? On what operating system?
1.0.8 just updated today. android sprint moment

Please provide any additional information below.

```

Original issue reported on code.google.com by `Tim.Re...@gmail.com` on 24 Feb 2010 at 6:39

**Comment by shivangbtech** [comment]
I am working on "voicemail-example-for-android"

URL: https://code.google.com/p/voicemail-example-for-android/wiki/Development

I have implemented server for it. When I sync voice message using IMAP from server. It's working fine in Motorola devices of android but not other devices like samsung, HTC, many others.

In motorola devices it shows voice mail in call logs but in other devices it is not showing desired voice message in call logs, Can you please help me to get rid this problem. It's very important for me. Please!!!

**Comment by shivangbtech** [comment]
I am getting exception below in SAMSUNG device:

10-05 18:09:05.237: E/VoicemailSample(26794): OmtpFetchController: Couldn't write payload to content provider
10-05 18:09:05.237: E/VoicemailSample(26794): java.io.IOException: Updating voicemail should have updated 1 row, was: 0
10-05 18:09:05.237: E/VoicemailSample(26794): 	at com.example.android.voicemail.common.core.VoicemailProviderHelpers.setVoicemailContent(VoicemailProviderHelpers.java:154)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at com.example.android.voicemail.common.core.VoicemailProviderHelpers.setVoicemailContent(VoicemailProviderHelpers.java:126)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at com.google.android.voicemail.example.service.fetch.OmtpFetchController.onHandleFetchIntent(OmtpFetchController.java:89)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at com.google.android.voicemail.example.service.fetch.OmtpFetchService.onHandleIntent(OmtpFetchService.java:71)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at android.os.Looper.loop(Looper.java:137)
10-05 18:09:05.237: E/VoicemailSample(26794): 	at android.os.HandlerThread.run(HandlerThread.java:60)
10-05 18:09:05.237: D/VoicemailSample(26794): OmtpFetchController: Received onHandleFetchIntent(Intent { act=com.google.android.apps.vvm.VOICEMAIL_FETCH dat=content://com.android.voicemail/voicemail/5?source_package=com.google.android.voicemail.example cmp=com.google.android.voicemail.example/.service.fetch.OmtpFetchService (has extras) })
